# Netlify configuration file

# Редиректы
[[redirects]]
  from = "https://www.lprospekt.com/*"
  to = "https://lprospekt.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.lprospekt.com/*"
  to = "https://lprospekt.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://lprospekt.com/*"
  to = "https://lprospekt.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/sepiia"
  to = "/sepiia/"
  status = 301

[[redirects]]
  from = "/movel"
  to = "/movel/"
  status = 301

# Настройки сборки (опционально)
[build]
  publish = "."
  command = "echo 'No build command'"